//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.5076.0
//
//     对此文件的更改可能会导致不正确的行为,如果
//     重新生成代码,这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace LYBox.Plugin.DouyinDownloader.Resources {
    using System;
    using System.Resources;
    using System.Globalization;
    using System.Threading;


    /// <summary>
    ///   强类型资源类,用于查找本地化字符串等。
    /// </summary>
    public class Strings {
        private static ResourceManager? _resourceManager;

        private static CultureInfo? _resourceCulture;

        /// <summary>
        ///   返回此类使用的、已缓存的 ResourceManager 实例。
        /// </summary>
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    var temp = new ResourceManager("LYBox.Plugin.DouyinDownloader.Resources.Strings", typeof(Strings).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager!;
            }
        }

        /// <summary>
        ///   使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性以匹配
        ///   使用此强类型资源类的所有资源查找。
        /// </summary>
        public static CultureInfo? Culture {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }


        /// <summary>插件主标题。</summary>
        public static string Plugin_Title {
            get => ResourceManager.GetString("Plugin_Title", _resourceCulture!) ?? "抖音下载器";
        }

        public static string Plugin_Description {
            get => ResourceManager.GetString("Plugin_Description", _resourceCulture!) ?? "";
        }

        public static string Nav_DouyinRoot => ResourceManager.GetString("Nav_DouyinRoot", _resourceCulture!) ?? "抖音下载";
        public static string Nav_DouyinSubmit => ResourceManager.GetString("Nav_DouyinSubmit", _resourceCulture!) ?? "提交下载";
        public static string Nav_DouyinJobs => ResourceManager.GetString("Nav_DouyinJobs", _resourceCulture!) ?? "任务中心";
        public static string Nav_DouyinHistory => ResourceManager.GetString("Nav_DouyinHistory", _resourceCulture!) ?? "历史记录";
        public static string Nav_DouyinSettings => ResourceManager.GetString("Nav_DouyinSettings", _resourceCulture!) ?? "设置";
        public static string Nav_DouyinLogin => ResourceManager.GetString("Nav_DouyinLogin", _resourceCulture!) ?? "登录";

        public static string Submit_UrlHint => ResourceManager.GetString("Submit_UrlHint", _resourceCulture!) ?? "";
        public static string Submit_Mode => ResourceManager.GetString("Submit_Mode", _resourceCulture!) ?? "下载模式";
        public static string Submit_Number => ResourceManager.GetString("Submit_Number", _resourceCulture!) ?? "数量限制";
        public static string Submit_StartDate => ResourceManager.GetString("Submit_StartDate", _resourceCulture!) ?? "";
        public static string Submit_EndDate => ResourceManager.GetString("Submit_EndDate", _resourceCulture!) ?? "";
        public static string Submit_Button => ResourceManager.GetString("Submit_Button", _resourceCulture!) ?? "加入下载队列";

        public static string Status_Ready => ResourceManager.GetString("Status_Ready", _resourceCulture!) ?? "就绪";
        public static string Status_Running => ResourceManager.GetString("Status_Running", _resourceCulture!) ?? "运行中";
        public static string Status_Failed => ResourceManager.GetString("Status_Failed", _resourceCulture!) ?? "失败";
        public static string Status_Success => ResourceManager.GetString("Status_Success", _resourceCulture!) ?? "完成";
        public static string Status_Skipped => ResourceManager.GetString("Status_Skipped", _resourceCulture!) ?? "已跳过";

        public static string Login_Tip => ResourceManager.GetString("Login_Tip", _resourceCulture!) ?? "";
        public static string Login_OpenQR => ResourceManager.GetString("Login_OpenQR", _resourceCulture!) ?? "打开登录页面";
        public static string Login_ReloadQR => ResourceManager.GetString("Login_ReloadQR", _resourceCulture!) ?? "刷新二维码";
        public static string Login_Manual => ResourceManager.GetString("Login_Manual", _resourceCulture!) ?? "手动粘贴 Cookie";

        public static string Settings_SignerUrl => ResourceManager.GetString("Settings_SignerUrl", _resourceCulture!) ?? "";
        public static string Settings_DownloadPath => ResourceManager.GetString("Settings_DownloadPath", _resourceCulture!) ?? "";
        public static string Settings_Concurrency => ResourceManager.GetString("Settings_Concurrency", _resourceCulture!) ?? "";
        public static string Settings_Proxy => ResourceManager.GetString("Settings_Proxy", _resourceCulture!) ?? "";
        public static string Settings_Webhook => ResourceManager.GetString("Settings_Webhook", _resourceCulture!) ?? "";

        public static string Msg_NoConfig => ResourceManager.GetString("Msg_NoConfig", _resourceCulture!) ?? "";
        public static string Msg_DuplicateUrl => ResourceManager.GetString("Msg_DuplicateUrl", _resourceCulture!) ?? "";
    }
}
